Repository kontena/k8s-client, pull requests merged in 2019-08, with the labels that each got.

#149 Don't validate the expired cert fixture in tests
  spec/k8s/transport_spec.rb
Labels: bug, chore

#151 Update excon to 0.66
  k8s-client.gemspec
Labels: chore

#153 Remove foo.yaml
  lib/k8s/foo.yaml
Labels: chore

#148 Update WebMock and Hashdiff dependencies
  k8s-client.gemspec
  lib/k8s/util.rb
Labels: chore

#154 Add kube node config files to autoconfig search paths
  lib/k8s/client.rb
  spec/k8s/client_spec.rb
Labels: enhancement

#158 Fix path prefix handling in server address
  lib/k8s/transport.rb
  spec/k8s/transport_spec.rb
Labels: bug

#142 Remove bin/k8s-client executable
  bin/k8s-client
Labels: chore

#127 Make Yajl dependency optional
  README.md
  k8s-client.gemspec
  lib/k8s/api.rb
  lib/k8s/client.rb
  lib/k8s/json_parser.rb
  lib/k8s/json_parser/yajl.rb
  lib/k8s/resource.rb
  lib/k8s/resource_client.rb
  lib/k8s/transport.rb
  lib/k8s/util.rb
  spec/k8s/json_parser_spec.rb
Labels: chore, enhancement

#147 Drop dry-* dependencies
  README.md
  k8s-client.gemspec
  lib/k8s/api.rb
  lib/k8s/api/metav1.rb
  lib/k8s/api/metav1/api_group.rb
  lib/k8s/api/metav1/api_resource.rb
  lib/k8s/api/metav1/list.rb
  lib/k8s/api/metav1/object.rb
  lib/k8s/api/metav1/status.rb
  lib/k8s/api/metav1/watch_event.rb
  lib/k8s/api/version.rb
  lib/k8s/api_client.rb
  lib/k8s/client.rb
  lib/k8s/config.rb
  lib/k8s/resource.rb
  lib/k8s/resource_client.rb
  lib/k8s/stack.rb
  lib/k8s/transport.rb
  lib/k8s/util.rb
  lib/k8s/watch_event.rb
  spec/k8s/api_client_spec.rb
  spec/k8s/client_spec.rb
  spec/k8s/config_spec.rb
  spec/k8s/resource_client_spec.rb
  spec/k8s/transport_spec.rb
Labels: chore, enhancement
