Repository kontena/k8s-client, pull requests merged in 2019-01, with the labels that each got.

#83 Try uncached api_resources before raising K8s::Error::UndefinedResource
  lib/k8s/api_client.rb
Labels: enhancement

#81 Replace deep_merge gem with own implementation
  k8s-client.gemspec
  lib/k8s/client.rb
  lib/k8s/resource.rb
  lib/k8s/util.rb
  spec/k8s/util_spec.rb
Labels: bug, enhancement

#87 Prefix in_cluster_config paths with $TELEPRESENCE_ROOT
  lib/k8s/transport.rb
  spec/k8s/transport_spec.rb
Labels: enhancement

#88 Pass options from K8s::Client.in_cluster_config to Transport
  lib/k8s/client.rb
Labels: bug, enhancement

#89 Handle errors better in pipelined Client requests
  lib/k8s/client.rb
  spec/k8s/client_spec.rb
Labels: bug

#94 Catch misbehaving kube api errors in Client#resources
  lib/k8s/client.rb
Labels: bug

#99 Fix K8s::Client.autoconfig when using KUBECONFIG
  lib/k8s/client.rb
  lib/k8s/resource_client.rb
  lib/k8s/stack.rb
Labels: bug
